### ISSUE TITLE
Detalles de la solicitud

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#113]
![image](https://github.com/user-attachments/assets/1e8c3117-4c8d-4c05-98f8-20e9def7687f)
integrante rechazo.
Admin de la GE confirmo  user: 100000000@est.umss.edu
                                          pass: Simon123@ 

![image](https://github.com/user-attachments/assets/9b47e6e8-c247-499d-894e-2781b4244139)

aparece el user 300000000@est.umss.edu que rechazo como si estuviera en el equipo.

**Comment by jh0nz** [comment]
ya esta, el numero de integrantes en la lista de empresas pendientes tambien estaba mal @Frosmin
