### ISSUE TITLE
553.1 Se necesita refrescar la página para que se recuperen los mensajes correctamente :/

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#115]
La primera vez que carga solamente se recuperan el nombre de la plantilla y su descripción, pero estos se sobreponen con el texto de los campos.
No se obtienen los criterios.
Hasta que se refresca la página es que ya se recuperan los datos correctamente.
![image](https://github.com/user-attachments/assets/cda41d2b-5a39-4e15-8f9a-34cb5c1e66b2)

**Comment by Richi78** [comment]
tu lo solucionaste con el refethonmount
