### ISSUE TITLE
553.2 No se respeta el orden colocado cuando los parámetros son mayúsculas

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#116]
1 -> Los parametros con mayúscula aparecen al final (ocasionando que sea dificil saber si el parametro representa algo bueno o malo)
2,3 -> Cambio el orden de los parametros en su lista, al Editar la plantilla
4 -> Al guardar los cambios y aparecer el circulo de carga, se reordenan a la parte de abajo :(

![image](https://github.com/user-attachments/assets/bd1aa4a6-febe-4517-9f4f-54b82adb74ff)

**Comment by Richi78** [comment]
cerrado
![image](https://github.com/user-attachments/assets/ea2b3fed-40c1-45ba-9f60-e18266d1d868)
