### ISSUE TITLE
553.3 Estas plantillas no pueden ser editadas

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#117]
Imagino que es porque ya se asignaron a una evaluación???
Pero no hay ningun mensaje que me avise que es de esa forma, o que me avise que sucede
(Da la impresión de que no funciona :P , pero para las otras plantillas si lo hace correctamente)

![image](https://github.com/user-attachments/assets/b92c680c-c213-4c1a-b430-f739bdb13ee3)

**Comment by Richi78** [comment]
ta bien
