### ISSUE TITLE
enviar confirmación de GE

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#118]
![image](https://github.com/user-attachments/assets/c600317b-7642-47ff-bdfe-92914412a227)
Empresa ya envió su confirmación y docente ya acepto la confirmación
La empresa puede volver a enviar las veces que quiera su confirmación 

User: 100000000@est.umss.edu
Pass Simon123@

**Comment by Frosmin** [comment]
@KevinOmega

**Comment by jh0nz** [comment]
ya
