### ISSUE TITLE
Crear evaluacion/evaluar

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#120]
Docente crea una evaluación 

Estudiante trata de resolver la evaluación 
![image](https://github.com/user-attachments/assets/69a2566c-ef10-4799-9509-5c620bd35279)

[image](https://github.com/user-attachments/assets/f23b3dbd-b13a-47cd-8386-bda90e5315eb)
User:100000000@est.umss.edu
Pass: Simon123@

**Comment by jh0nz** [comment]
ya esta creooo
