### ISSUE TITLE
Editar plantilla de evaluacion

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#121]
Crear una plantilla de evaluación con nombre hola
Crear una segunda plantilla de evaluación con nombre hola2 (diferente a la primera)

Editar la planilla hola2 y cambiarla al nombre hola
![image](https://github.com/user-attachments/assets/84c7255b-9c9f-4c55-af85-c71f87d5e78f)

ahora tendríamos el mismo nombre en 2 plantillas

![image](https://github.com/user-attachments/assets/2cbe6534-915b-4dc6-9df3-c30ebcb607fa)

**Comment by Frosmin** [comment]
User un docente  simon@fcyt.umss.edu.bo
Pass Simon123@

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/25b07771-3d09-4aca-8b91-824f4cb52037)
@Frosmin ya esta reportado este bug

**Comment by Richi78** [comment]
@Jh0nZ

**Comment by Frosmin** [comment]
disculpe joven @Richi78
