### ISSUE TITLE
Crear evaluacion

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#125]
![image](https://github.com/user-attachments/assets/a7374a5e-6c5e-4993-b98b-cd99296cc832)
Las fechas de inicio y de fin no son fechas válidas si se ingresan valores mayores a la fecha de fin del periodo académico.

![image](https://github.com/user-attachments/assets/6b5fe5da-a941-4ff2-8b07-eb98c144cba5)
Inicio fin 

No esta controlando la fecha de fin del periodo academico

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/c3c4ff39-8e15-4de8-bd40-9624e3b71585)
![image](https://github.com/user-attachments/assets/a55aeafb-bd6e-4a2b-a2ba-75e364ceeac6)

son validaciones del back @Daye0210 @Jh0nZ

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/1baec53c-2995-4b75-97a8-61b3391ff5a9)
![image](https://github.com/user-attachments/assets/55a2f02c-d5a6-4fb1-a729-4abbd777feb1)
incluso en fechas que estan dentro del periodo de evaluacion, 

veo que no se estan enviando bien las fechas 
![image](https://github.com/user-attachments/assets/c8f5032b-04ca-4f85-b63f-b923313b6c20)
![image](https://github.com/user-attachments/assets/a9475fee-d799-4924-b848-d17fb3ef4ace)
solo considera el dia que esta creando la evaluacion y no el dia que esta poniendo en los inputs
