### ISSUE TITLE
Elementos muy grandes para Ver Solicitudes

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#128]
Ver solicitudes de creación de grupo empresas ocupan mucho campo, haciendo que haya mucho scroll (la inge dijo que es recomendable evitar mucho scroll)

![image](https://github.com/user-attachments/assets/345c423f-1f8b-429b-a22f-b116868b6fbf)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/634b106b-e99d-4197-9599-571304d0bf87)
cambie las cards a unas similares a las de ver GE, para aceptar/rechazar aparece el botoncito

![image](https://github.com/user-attachments/assets/5e943c8c-3847-45a9-8cf6-1ad331173cd3)
