### ISSUE TITLE
Mensaje incorrecto al validar el nombre del periodo academico en Registro de Periodo Academico

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#129]
Ingresé un texto largo en el nombre, y fechas que no creo que respeten el periodo academico. Presioné "REGISTRAR PERIODO" y me indica que el nombre ya está en uso, lo cual no es cierto :/

![image](https://github.com/user-attachments/assets/39c33432-5be4-4c38-940a-b03b32f103e6)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/2c1ccbb8-7cac-4ca8-bcd3-f0abf8d32bda)
ya muestra el mensaje correcto, falta el espa;olizado
@Jh0nZ
