### ISSUE TITLE
Registro academico no muestra mensajes de retroalimentación

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#130]
Despues de haber ingresado un nombre largo, intentar validarlo al presionar el botón "REGISTRAR PERIODO", salir el mensaje de error "nombre ya en uso" (que no era cierto)...

Reduje el nombre del periodo academico, y ahora al presionar el botón, se carga la página pero no sucede nada en pantalla

El mensaje de la consola dice: "El campo start date debe ser una fecha posterior o igual a today.", pero no se avisa al usuario en ningún momento qué está mal y porque no puede proceder con el registro

![image](https://github.com/user-attachments/assets/6015cd94-5e9a-45df-aebf-600ae225d0ed)

**Comment by Richi78** [comment]
ya muestra mensajes de retroalimentacion
