### ISSUE TITLE
Acceso repetido a ACEPTAR/RECHAZAR Solicitudes de GEs

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#132]
Se puede acceder desde ambos lugares a la página de aceptar y rechazar solicitudes ¿Es esto correcto? En caso de que no, corregir. En caso de que si sea correcto, Marcar el issue como resuelto

![image](https://github.com/user-attachments/assets/e709fb44-f56a-4cf8-a457-6020cb006a41)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/0af43b1a-5226-46eb-8bc7-17ad6f824593)
boton funado
