### ISSUE TITLE
Posiciones y espaciados entre elementos poco apropiados en el student Home

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#134]
El contenedor de invitaciones se encuentra muy pegado a la parte inferior de la pantalla

El botón de ACEPTAR/RECHAZAR Invitaciones deberia estar en el centro, pero se desplazó al lado derecho. Esto es por la propiedad "space-between" del contenedor

El espaciado entre los contenedores Taller TIS e Invitaciones es demasiado grande

![image](https://github.com/user-attachments/assets/b72eb8d9-b1bd-4e6b-bf9d-02c66ec63213)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/177396a6-38be-4f37-9227-15dbdabaf525)
![image](https://github.com/user-attachments/assets/b5b7aac8-fda4-4e4e-bc83-b07a1741bd75)
se reducio el espaciado, el boton aceptar/rechazar ya no esta en el costado y ya no esta muy pegado a la parte inferior de la pantalla
