### ISSUE TITLE
La HU Ver Plantillas no tiene un titulo

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#145]
Esta no es una HU como tal, pero por temas de navegación la página si necesita tener un titulo :P

![image](https://github.com/user-attachments/assets/5238fc0b-7f61-4e22-a041-5d7973fb4b18)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/ac0b2335-01d8-4a48-a32d-8f4b7abb8560)
ya tiene titulo :D
