### ISSUE TITLE
El mensaje "Debes validar los hitos anteriores..." no corresponde si es el primer hito mostrado en pantalla

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#150]
Este mensaje aparece cuando se desmarca un entregable de Carry Over

Además indica que este hito ya ha sido validado, por lo que no tiene sentido que me pida algo para poderlo validar 

![image](https://github.com/user-attachments/assets/8fe7d598-1b23-4835-8cb0-776ea02d6113)

**Comment by KevinOmega** [comment]
No puedo replicar el error, cuando pasa?
