### ISSUE TITLE
El registro de estudiante no redirige a ningún lado despues de registrar los datos de la cuenta

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#153]
Lleno los datos, mando el formulario, y no redirige a ningún sitio, dando la impresión de que no se envio

Le doy a registrar otra vez, y me indica que el correo ya está en uso

![image](https://github.com/user-attachments/assets/365c8895-f9b7-4f93-8986-26bc2c57a61d)

**Comment by Richi78** [comment]
ta raro, si redirige
![image](https://github.com/user-attachments/assets/2ca53e44-fa08-4dfe-b6a3-7a9317bd01a2)
