### ISSUE TITLE
El registro de estudiante no avisa que se ha registrado correctamente

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#154]
Además de no redirigir a ningun sitio tras enviar el formulario, tampoco avisa que se ha registrado o no los datos del usuario para la creación de una cuenta de estudiante

![image](https://github.com/user-attachments/assets/4f9be2ea-ee6e-4c1c-bc2e-1e4927aba03c)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/42ab5c05-728b-4b13-bf02-6a6837223de3)
raro, si avisa
