### ISSUE TITLE
Diferentes tamaños para los botones de las invitaciones en el student-home

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#155]
![image](https://github.com/user-attachments/assets/201b4954-89a2-4820-97ce-8c6f67fc8568)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/c1860a0c-d276-4ce3-a8f6-907747500b88)
al aumentar texto se igualaron los tama;os ✌️
