### ISSUE TITLE
No hay retroalimentación en el número de telefono en la HU Registrar GE

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#156]
No indica qué es un número válido, solamente dice "Error de validación"

![image](https://github.com/user-attachments/assets/7629c282-a7ac-4011-a5e7-a3be634e28b4)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/e1be35ab-94ff-4e35-9621-98a104916327)
el mensaje de error esta bien, el snackbar dice error de validacion y en el campo celular muestra que el celular no es valido
