### ISSUE TITLE
El campo de número de celular indica que es válido para 7 u 8 digitos, pero es obligatorio que sea de 8 digitos para ser un número válido

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#157]
![image](https://github.com/user-attachments/assets/afcb40a6-bac3-4615-8123-535755a31266)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/d4f77c0d-3406-4ce9-a3b4-6211a996fd8b)
mensaje cambiado
