### ISSUE TITLE
El modal de registro exitoso dice "periodo academico" pero la HU dice "grupo TIS"

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#160]
En los criterios de aceptación ya se cambiaron para que digan "grupo TIS" de acorde al nombre de la HU

![image](https://github.com/user-attachments/assets/4f3a6dab-1869-4b62-ba38-29502af6e4be)
![image](https://github.com/user-attachments/assets/e952ccbb-b994-4baf-8d74-af08603103c6)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/0b2b79ad-e69b-4c93-9ef9-7835b995362c)
se cambio a grupo TIS, no creo que sea un grupo de gestion de proyectos @erwinparedez
