### ISSUE TITLE
Cambiar el mensaje de Retirar Invitaciones Pendientes

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#162]
Cambiar el texto "Lista de Invitaciones a Retirar:" a "Estudiantes que aún no han aceptado la invitación" o similar

También se puede cambiar el titulo "Invitaciones Pendientes" por "Retirar Invitaciones" o similar

Mejora la redacción

![image](https://github.com/user-attachments/assets/7eb0b6cb-0ed4-43e7-8a73-f3034a5ff78e)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/049a2399-5864-48be-942f-d8ab94623095)
Texto cambiado
