### ISSUE TITLE
Demora al invitar a un estudiante (no sé si realmente es un bug)

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#163]
Al invitar a un estudiante, El mensaje "Invitación creada exitosamente" aparece, no pasa nada, y luego reaparece con el estudiante agregado a la lista, segundos después

![image](https://github.com/user-attachments/assets/35a2f599-63ef-4e56-b5e6-7956ea489fd4)

**Comment by KevinOmega** [comment]
Culpa del back
