### ISSUE TITLE
Registrar periodo academico

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#164]
![image](https://github.com/user-attachments/assets/b50b3f88-1e7d-40ba-badf-805661952842)
No se puede crear un segundo periodo academico 
Tampoco muestra nungun mensaje de retroalimentación 
user.: simon@fcyt.umss.edu.bo
pass: Simon123@

**Comment by jh0nz** [comment]
Falta validar la fecha inicio posterior a hoy dia en el front, el mensaje del back lo devuelve feo

**Comment by Richi78** [comment]
esta en closed, ya lo solucionaron verdad?, en si se deberia mostrar mensajes del back, deberian enviarlo en espa;ol xd
y la fecha de inicio si podria ser el mismo dia, incluso el mensaje del back lo dice, posterior o igual
![image](https://github.com/user-attachments/assets/c562f4b9-5cad-466c-9faa-2eb8c043b04d)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/471a5ffd-d04f-432d-a77b-eac0a0cf1304)

ya muestra los mensajes, esta enviando bien las fechas y esta retornando esos errores, o no se en que formato se deberia enviar al back
@Jh0nZ

**Comment by jh0nz** [comment]
Lo reviso
