### ISSUE TITLE
Malas fechas de periodo 

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#165]
El periodo academic fue creado con un inicio el 2/11/2024
fecha mostrada de inicio 1/11/2024
![image](https://github.com/user-attachments/assets/9b597851-3e91-4d44-aece-e65b9a91ea79)

User:simon@fcyt.umss.edu.bo
pass: Simon123q

**Comment by jh0nz** [comment]
revisa todas las fechas y horas
