### ISSUE TITLE
No se cumplen los criterios de mostrar que se ha aceptado o rechazado correctamente

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#171]
No se muestran los mensajes que dicen los criterios

Se redirige al student-home en su lugar

![image](https://github.com/user-attachments/assets/75cbe245-bb59-40da-9562-86cde608a196)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/3db03b32-8261-4388-9d0b-a601d8a80c91)
![image](https://github.com/user-attachments/assets/76b48a2d-8e3b-4419-99c8-17a814bf69aa)
ya muestra

**Comment by Richi78** [comment]
me doy cuenta que esta mostrando solicitud en lugar de invitacion jaja, @Jh0nZ cambia el mensaje que el back retorna plox, es de aceptar/rechazar invitacion de grupo empresa
