### ISSUE TITLE
Falta de consistencia: Dice "Teléfono" pero en el rellenado del Formulario para crear la GE es "celular"

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#173]
![image](https://github.com/user-attachments/assets/2c81f303-58ed-4edc-adca-fcdccb5e1f85)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/6e148347-f3d8-44ac-ab46-4bdaf98daed5)
ya ta con celular
