### ISSUE TITLE
Dice "invitación" y debe ser "solicitud" en el modal de los detalles de la solicitud

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#175]
![image](https://github.com/user-attachments/assets/51b0a3a3-29e0-46cc-a3ba-dec019229f96)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/6a904916-22f0-4f55-ab6e-c612fcd65483)
![image](https://github.com/user-attachments/assets/c9bcb1db-26e0-442d-86a9-8620f654e9ca)
ya muestran mensajes correctos
