### ISSUE TITLE
Criterios de mostrar mensaje de solicitud aceptada/rechazada correctamente no se cumplen

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#177]
Entrar a la solicitud y presionar rechazar, muestra que se ha actualizado exitosamente

Deberia indicar si se ha aceptado o rechazado correctamente

![image](https://github.com/user-attachments/assets/c6d454f2-306f-4d89-b125-9c17be482060)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/1e08a177-d57d-4ee6-99b5-01ce9b382440)
![image](https://github.com/user-attachments/assets/328869ff-6614-4586-aba2-98233442bc6c)
ya muestran los mensajes correctos + activarwindows :D
