### ISSUE TITLE
Tamaño (altura) de los botones del home docente, desproporcionales

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#178]
Los botones tienen diferentes tamaños según la cantidad de texto

![image](https://github.com/user-attachments/assets/617d6ca8-d53e-4439-be59-e8e1ba8a4c0e)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/6d2a1334-762d-4223-8413-c91ca9c73ff4)
