### ISSUE TITLE
Las fechas del seguimiento semanal no pertenecen a una misma semana

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#179]
Entré a la lista para el seguimiento semanal, Miercoles y Jueves pertenecen a fechas de Diciembre, mientras que Lunes y Sabado están en la primera semana de Noviembre (que corresponden a la fecha actual, hoy es 02/11/2024)

![image](https://github.com/user-attachments/assets/31fdd0d1-739f-43f4-821b-e563ac8bd7f7)

**Comment by KevinOmega** [comment]
No es un bug.
En el campo "Dia de entregable" sale la fecha que le toca entregable a la grupo empresa.
Por esa razon los que su entregable no les toca esa semana tienen arriba de su nombre "Revision" por que no les toca entregable esa semana
