### ISSUE TITLE
Las fechas del seguimiento semanal no son correctos

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#180]
No coinciden las fechas

![image](https://github.com/user-attachments/assets/aed9f3cb-f330-4789-a5c3-ea0ec19a20ce)

**Comment by KevinOmega** [comment]
Las fechas si son correctas, en realidad no es un bug, sale diferente al validar la planificacion, por que tiene la validacion de entregables anteriores pendientes. Talvez seria bueno agregar un nuevo criterio para indicar que una grupo empresa tiene una validacion pendiente
