### ISSUE TITLE
Bug al Registrar una cuenta, como estudiante o docente

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#186]
Al Registrar a un docente no redirige a ninguna parte y despues al volver a registrar sale que el correo ya esta en uso

![image](https://github.com/user-attachments/assets/25e0d07e-48fd-46be-ac90-b01485597bcd)

**Comment by Frosmin** [comment]
x2

**Comment by Richi78** [comment]
parece que esta mostrando el error equivocado, deberia poner 9 digitos nove, seguro los mensajes de error no contemplan todos los casos

**Comment by Richi78** [comment]
no pude reproducir el issue, se creo correctamente el usuario y redirige a una pagina de confirmacion
![image](https://github.com/user-attachments/assets/8ff37088-cbaa-47aa-9a86-f8de37671c39)
![image](https://github.com/user-attachments/assets/0eb9340a-8ab5-430a-b32d-d9f0d774b61e)
