### ISSUE TITLE
Error al registrar un periodo academico (Error al convertir las fechas)

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#187]
Al registrar un periodo academico sale el mensaje "Ha ocurrido un error inesperado"

`"Could not parse '31/12/2024, 00:00:00': Failed to parse time string (31/12/2024, 00:00:00) at position 0 (3): Unexpected character"
`

![image](https://github.com/user-attachments/assets/732d1fed-af15-44b0-8d27-d5cc96f197ab)

**Comment by jh0nz** [comment]
borra el vendor y composer install @KevinOmega

**Comment by Richi78** [comment]
no me da ningun error
