### ISSUE TITLE
Rechazar  invitacion GE

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#189]
![image](https://github.com/user-attachments/assets/f7d8574c-be97-4aea-b3a7-742140a96df9)
Rechazo y sale ese message 

user: 000033333 
pass: Simon123@

**Comment by Richi78** [comment]
parece que ya aceptaste a otra GE y por eso te sale ese error
![image](https://github.com/user-attachments/assets/854cbafe-63c1-4b0a-acf7-25918dad1403)
hice la prueba y me sale el mensaje bueno
