### ISSUE TITLE
Error al invitar estudiante 

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#190]
Al enviar una invitacion a un estudiante, cuando no este no pertenece a una grupo empresa la invitacion ser realiza de manera exitosa, sin embargo cuando este acepta estar en otra grupo empresa, la invitacion realizada sigue figurando en la lista de invitaciones
![image](https://github.com/user-attachments/assets/6888a4b6-cc95-43af-9e4f-543e46dbdd4f)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/24a01a98-f6d4-48ac-b38b-2747c1df0982)
no pude replicar la issue, todo salio bien
solo es dar f5 porque no se actualiza en tiempo real las paginas
