### ISSUE TITLE
Ajustar las fechas del Periodo academico permite ingresar fechas anteriores a la fecha actual

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#192]
Cree un periodo academico del 1 al 31 de Diciembre (teniendo en cuenta las restricciones de las fechas, ej: que el periodo dure al menos 3 dias, no se insertan fechas anteriores, etc.)
Al momento de querer cambiar las fechas en la HU "Ajustar periodo academico" no se están respetando esas restricciones, y me permite ingresar FECHAS ANTERIORES A LA FECHA ACTUAL
![image](https://github.com/user-attachments/assets/6c25eeed-03b4-41bc-a5eb-8d5d647a7ea1)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/fa5b82cf-4689-479c-8aaf-b8f05738e2e2)
