### ISSUE TITLE
Ajustar la fecha del periodo academico indica que colocar fechas iguales es válido, pero no es cierto

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#194]
Al ajustar la fecha e introducir una Fecha de Inicio posterior a la Fecha de Fin, sale el mensaje: "La fecha de fin debe ser mayor o igual que la fecha de inicio", que indica que una fecha igual en ambas es válida, y esto no es cierto, porque al poner fechas iguales en ambos campos también muestra un mensaje de error
![image](https://github.com/user-attachments/assets/b897f3d3-08dc-4888-b57b-4849ca92035a)
![image](https://github.com/user-attachments/assets/ecf49c74-2136-4180-a499-4efe42def2ac)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/8100832d-711a-4851-bee8-c31312d84c3e)
fecha fin tiene que se mayor a fecha ini
