### ISSUE TITLE
Cuando no hay calificaciones, deberia mostrarse un mensaje indicando que no hay calificaciones en lugar de un "0" xd

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#195]
"Ver calificaciones de grupo empresa" muestra "0" cuando no hay calificaciones que ver de las grupo empresas
![image](https://github.com/user-attachments/assets/5b5e5c5d-e9d7-48fe-aaeb-e845e7e04977)

**Comment by Richi78** [comment]
@KevinOmega
