### ISSUE TITLE
Cuando no hay calificaciones de los estudiantes, deberia mostrarse un mensaje indicando que no hay calificaciones en lugar de un "0"

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#196]
"Ver calificaciones de estudiantes" cuando no hay calificaciones
![image](https://github.com/user-attachments/assets/a9427ee0-24dd-4a27-9bce-77ed864a641e)

**Comment by Richi78** [comment]
@KevinOmega
