### ISSUE TITLE
Crear una evaluacion para el ultimo dia del periodo academico no es una fecha válida

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#198]
El periodo academico es del 1 al 31 de Diciembre, intento colocar la Evaluación para el último dia del periodo academico, pero me indica que estoy fuera de las fechas, y no es cierto.

![image](https://github.com/user-attachments/assets/85154ed0-bfdf-4227-b724-e31226968ca2)

**Comment by Richi78** [comment]
me sale el mismo error
![image](https://github.com/user-attachments/assets/aef107e0-7a9f-43f7-9194-53e88fe99cb7)
las fechas se estan enviando bien
![image](https://github.com/user-attachments/assets/089da7c0-0cf1-48b5-b077-6830c59c71cd)
@Jh0nZ @Daye0210

**Comment by Richi78** [comment]
no usar el ultimo dia :D

**Comment by KevinOmega** [comment]
Solucionado por @Richi78
