### ISSUE TITLE
Qa's relaten bien sus bugs

### ISSUE THREAD

**Issue by jh0nz** [Api-programming-company/TisTracker#20]
**1. Título claro y descriptivo:**

    El título debe resumir el problema de manera concisa.
    Ejemplo: "Error al guardar información en el formulario de registro de usuarios".

**2. Descripción detallada:**

    Explica el problema con claridad, proporcionando detalles de qué es lo que está ocurriendo.
    Usa un lenguaje técnico cuando sea necesario y describe lo que esperabas que sucediera en lugar de lo que ocurrió.

**3. Pasos para reproducir:**

Proporciona una lista paso a paso para que el equipo de desarrollo pueda reproducir el error:

    Ir a la página de registro de usuario.
    Completar el formulario con información válida.
    Hacer clic en "Enviar".
    Observar el error en pantalla (el formulario no se guarda y no se muestra mensaje de confirmación).

**4. Resultados esperados:**

Explica lo que se esperaba que sucediera si el sistema funcionara correctamente:

    "El sistema debería guardar la información y mostrar un mensaje de confirmación: 'Registro completado con éxito'."

**5. Resultados reales:**

Describe lo que realmente sucedió:

    "El sistema no guarda la información, no se muestra ningún mensaje de confirmación, y el formulario permanece en la página."

**6. Evidencia (adjuntar archivos):**

    Incluye capturas de pantalla, videos, o archivos de logs si es necesario. Esto ayudará a visualizar mejor el problema.

**7. Entorno (Environment):**

Proporciona información técnica sobre dónde ocurrió el problema:

    Sistema operativo: Windows 10 / macOS 12.
    Navegador: Chrome 95.0 / Firefox 92.0.
    Versión del software: v1.0.3.
    Base de datos: PostgreSQL 12.

**8. Prioridad (opcional):**

Indica la severidad o impacto del bug:

    Alta: El bug impide el uso de una funcionalidad crítica.
    Media: Afecta una funcionalidad importante, pero hay una solución temporal.
    Baja: Bug menor que no afecta de manera significativa la experiencia del usuario.

**Comment by Frosmin** [comment]
no kiero
