### ISSUE TITLE
"Ajustar periodo academico" me obliga a que todas las fechas que cambie, siempre empiecen en mi fecha actual

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#205]
Si intento ampliar el periodo academico 2 semanas más, me indica que la fecha inicial no puede ser menor a la fecha actual. No deberia restringirme si solo deseo ampliar la fecha final. Ya que puede que las GE ya hallan registrado sus planificaciones y demás, y mi anterior fecha inicial sea la correcta.
Hoy es 30/11/2024

![image](https://github.com/user-attachments/assets/ae5b3d5c-5977-4685-bda3-2bd0d21ad1ab)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/301bab41-908f-4b01-96ab-9a7f12ab170d)
no pude replicar la issue, pon mas detalles, quiza incluso la cuenta

**Comment by Richi78** [comment]
tiene sentido, hace rato habia otra issue que la fecha no puede ser menor a la actual, por eso lo puse
lo quito
