### ISSUE TITLE
Al entrar a "Ver reporte de evaluaciones semanales" en la cuenta del Boris, me sale error de código

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#206]
![image](https://github.com/user-attachments/assets/56b9549a-5440-4381-8475-ed0c90e39be5)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/ad15a429-b2ce-48f8-91c7-7b2dffbdb90c)
no pude replicar la issue
@erwinparedez
