### ISSUE TITLE
Entrar a "Lista de grupo empresas" me sale en blanco, y error en consola

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#207]
Ingresé con la cuenta del Boris, y luego a "Lista de grupo empresas", tarda en cargar, y luego sale en blanco la página. Es extraño porque para "Aceptar/Rechazar Solicitudes" si me salen elementos ha visualizar. Pero aqui no :/

![image](https://github.com/user-attachments/assets/7a78caf6-5aed-4eab-a17c-3ea8861a5878)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/ee922f53-c3d1-477c-b8e6-fc849b3668b2)
No pude replicar la issue, no sale ni un error por consola
@erwinparedez
