### ISSUE TITLE
Entrar "Ver grupo empresas para seguimiento semanal" me sale en blanco y error en consola

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#208]
Entré con la cuenta del Boris, luego a "Ver grupo empresas para seguimiento semanal" y no carga nada, y sale error en consola

![image](https://github.com/user-attachments/assets/3a49ce9d-493f-4edf-a3f7-d04c76a02cd7)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/535bb464-a28b-46bc-821e-e278ffe1d7a4)
No pude replicar la issue, no sale ni un error por consola
@erwinparedez
