### ISSUE TITLE
Entrar a "Ver calificaciones de grupo empresas" no está mostrando las notas, muestra "0" y sale error en consola

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#209]
Tardó muchisimo en cargar la página, y al final no salió nada
Entré con la cuenta del Boris, luego "Ver calificaciones de grupo empresas" y salió eso

![image](https://github.com/user-attachments/assets/e67f82ea-07b3-4bf2-a317-a1b4eba1bb49)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/f1d98904-eec5-4f36-b88b-9781cab6a315)
si sale esa vista, ningun error por consola, quiza sea tu conexion a internet y la peticion da un timeout
@erwinparedez 
@KevinOmega  que debe salir en lugar de ese 0?
