### ISSUE TITLE
Entrar a "Ver calificaciones de estudiantes" no está mostrando las notas, muestra "0" y sale error en consola

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#210]
Cuenta del Boris y luego "Ver calificaciones de estudiantes"

![image](https://github.com/user-attachments/assets/3d232bcb-faf9-4164-80ca-efe18e3718e2)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/c8659527-523d-4737-8b5b-47355ac77368)
La vista ta bueno, el error por consola no lo puedo replicar

@KevinOmega otra vez el 0 xd
