### ISSUE TITLE
Después de crearme una cuenta no me redirige a ningun lado, ni me avisa si me registré correctamente o no (ESTUDIANTE y DOCENTE)

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#212]
Despues de crearme una cuenta y presionar el boton de registro, carga la página pero luego me muestra el mismo formulario con mis datos como antes de mandarlo. Es decir, no me muestra nada que me diga que me registré de manera correcta, y tampoco me redirige a ningún sitio.
ESTE BUG VALE X2, PORQUE SUCEDE EN CREAR CUENTA PARA DOCENTE Y EN ESTUDIANTE
![image](https://github.com/user-attachments/assets/a33eb52a-9161-4d23-9152-3bf396223d8b)

![image](https://github.com/user-attachments/assets/ef2d56fb-5642-4455-9f57-c9fec6d14ca6)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/b98f2eec-4023-48f7-9e6e-7bc4b9176a8f)
no pude replicar la issue @erwinparedez
