### ISSUE TITLE
"Registro de Grupo empresa" no tiene retroalimentación sobre el número de telefono y fuerza a que sean 8 digitos para ser válido

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#213]
Ingresar un número de 7 digitos no es válido (y no me indica porque no es un número válido, cuando si deberia serlo)
Solo me permite ingresar numeros de 8 digitos para que sea un número válido

![image](https://github.com/user-attachments/assets/4d94556a-353a-40cb-8b2b-7940730cfa47)

**Comment by Richi78** [comment]
se debe ingresar un celular, los numeros de celular tienen 8 digitos,
