### ISSUE TITLE
"Agregar Planificacion" -> Porcentaje de facturacion no tiene retroalimentacion cuando se ingresan numeros decimales

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#216]
Ya sea con un numero decimal "10,5" o "10.5" me sale que hay un error de validación pero no me indica cual es. Si tuviera muchos entregables registrados, seria muy dificil saber cual fue el error (considerando que solo soy un usuario)

El formulario fue valido cuando borré el decimal y solo puse "10"

![image](https://github.com/user-attachments/assets/cccad402-8426-4e93-b24b-34265ffc3d9e)
![image](https://github.com/user-attachments/assets/b5d29972-ceb0-4da0-9bea-988e99d08aa0)

**Comment by KevinOmega** [comment]
Ahora ya no deja agregar numeros decimales, solo una  "," pero no pasa nada si la envia asi
