### ISSUE TITLE
Al docente le salen los botones para evaluar estudiantes

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#224]
![image](https://github.com/user-attachments/assets/23f66f6c-ddb8-4455-b7e1-ae9a8de8a0d3)

Al ingresar con una cuenta de docente, ver la lista de grupo empresas y  seleccionar una empresa, el docente tiene acceso  a evaluar a los estudiantes.

Credenciales del docente: 

**correo** : josemourinho@fcyt.umss.edu.bo
**password**  : Docente1234

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/0fe7d4c7-f8a6-40ff-85eb-3b826d4a0729)
ya lo solucionaron
