### ISSUE TITLE
Error al crear un nuevo entregable

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#225]
Cuenta : josemourinho@fcyt.umss.edu.bo
contra: Docente1234*
url: http://localhost:3000/weekly_tracking/2

Al agregar entregables sale el siguiente error:

"El campo milestones.2.deliverables.4.id seleccionado no existe."

**Comment by jh0nz** [comment]
no pude reproducir @KevinOmega, agrega mas detalles
