### ISSUE TITLE
Cambio de nombres entre entregables al agregar nuevos

### ISSUE THREAD

**Issue by jh0nz** [Api-programming-company/TisTracker#226]
![image](https://github.com/user-attachments/assets/95c70802-4817-494b-8bc7-85743f56cf48)
al agregar el 6 entregable, al escribir el nombre se cambia el nombre del entregable 4 tambien,  todo esto en el hito 3
Y a partir de agregar el 10mo entregable se cambia el nombre junto al entregable 1, el 11 con el 2 y asi...
![image](https://github.com/user-attachments/assets/05d33093-898a-43f7-b6ac-e9f205e8049a)

**Comment by KevinOmega** [comment]
Arreglado
