### ISSUE TITLE
Al registrar una nueva grupo empresa

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#23]
![image](https://github.com/user-attachments/assets/aaaa9698-01f6-4901-9d37-5b1b59a9a346)
Deja ingresar un correo hola@gmail
Que no tiene el dominio (.com, .onion, etc)

**Comment by Frosmin** [comment]
se entiende ? @Jh0nZ

**Comment by jh0nz** [comment]
mejorar el titulo pero
