### ISSUE TITLE
Las fechas se aumentan en uno al valor establecido

### ISSUE THREAD

**Issue by erwinparedez** [Api-programming-company/TisTracker#236]
Vista Docente:
![image](https://github.com/user-attachments/assets/20c43c4b-e41b-44d0-91a9-282d3c730a5b)
Vista Estudiante: La fecha de inicio y de fin están incrementados en uno
![image](https://github.com/user-attachments/assets/1e060a84-6757-4078-8800-12c805d5c160)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/0a6cb06e-376b-425a-afae-1314b6b28591)
solucionado
