### ISSUE TITLE
NO hay manera de que el docente pueda ver en que fechas puede asignar una evaluacion

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#240]
![image](https://github.com/user-attachments/assets/cf405f06-26d8-4810-877c-52ca829238b1)
![image](https://github.com/user-attachments/assets/3391287e-a0a5-4bb3-8844-a6f75324223c)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/2432c3f2-7955-4db9-9a1b-7cfab7a363f1)
