### ISSUE TITLE
Puedo crear parametros infinitos

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#241]
![image](https://github.com/user-attachments/assets/21b45f7c-a51e-4474-a1bb-3295a88240ce)

**Comment by Richi78** [comment]
Al darle click a crear la plantilla te muestra el mensaje de error y no envia nada al back
![image](https://github.com/user-attachments/assets/c5142138-989b-47ca-bf93-266dcd16c7b5)
![image](https://github.com/user-attachments/assets/08c3cbbd-609d-4238-8042-39da10b2fda4)
