### ISSUE TITLE
NO hay manera de volver al menu del periodo academico despues de editar la plantilla, a no ser de presionar el logo

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#242]
![image](https://github.com/user-attachments/assets/76d29b06-88f2-45b9-a229-18a51a55dc85)
![image](https://github.com/user-attachments/assets/99832390-e4df-4f64-b70a-8ad8a6549035)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/8bdd8be2-a4c1-4c6e-a90b-d219d5805997)
El botoncito regresa al menu de periodos academicos
