### ISSUE TITLE
Me deja crear una evaluacion con una fecha menor a la actual

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#245]
![image](https://github.com/user-attachments/assets/4ce7481b-8f75-4dc0-ae08-24723e591977)
![image](https://github.com/user-attachments/assets/f9884d4b-885a-47ea-a77f-b18471059628)

**Comment by Richi78** [comment]
@KevinOmega 
no puedo replicar la issue
![image](https://github.com/user-attachments/assets/0124be61-a80e-4548-a742-c3741b5cabe9)
en el calendario solo estan habilitados las fechas que estan en el rango
