### ISSUE TITLE
Ver resultado de evaluaciones semanales - No se puede ver, se cae a pedazos

### ISSUE THREAD

**Issue by Richi78** [Api-programming-company/TisTracker#248]
Estudiante: 192168201@est.umss.edu
Password: Estudiante1234*

![image](https://github.com/user-attachments/assets/e480d6b9-31e1-4751-9ab1-8c58ec35f028)

Pasos
1. En el home click a Mi Grupo Empresa
2. Click a Ver seguimiento semanal

Probando en el localhost se ve mas detalles
![image](https://github.com/user-attachments/assets/23072f66-1a4f-4cae-bfcf-819f1cd37534)

**Comment by KevinOmega** [comment]
Arreglado
