### ISSUE TITLE
Validacion de hito - No se puede realizar ninguna accion en entregables estaticos

### ISSUE THREAD

**Issue by Richi78** [Api-programming-company/TisTracker#249]
Docente: josemourinho@fcyt.umss.edu.bo
Password: Docente1234*

Empresa: Software House

![image](https://github.com/user-attachments/assets/26e53a5a-43a4-4aa0-a2e7-84fc16181ad9)

Validacion de hitos corresponde a la etapa en que se realiza una entrega y el docente puede poner los resultados esperados, observaciones, etc. En la captura es un hito 3 en estado pendiente, y en los entregables de tipo estatico no puedo modificar ningun campo, 

![image](https://github.com/user-attachments/assets/e2f952ea-1caf-4ac2-875b-bb41867b0925)

En la misma empresa en el hito 4 se observa entragables estaticos y en ninguno puedo poner observaciones, ni resultados esperados, etc. Como no se realiza ningun cambio el boton de confirmar nunca se habilita

**Comment by KevinOmega** [comment]
Arreglado, ahora todo menos el carry over se puede editar en los estaticos
