### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by Richi78** [Api-programming-company/TisTracker#25]
En el componente UserRegister se lleno los datos en el forms y y al darle registrar sale que el correo no es valido 
![image](https://github.com/user-attachments/assets/2dcab4f4-2a1c-4370-94eb-36a2f31fcd76)

**Comment by Richi78** [comment]
El mensaje de error es incorrecto, en este caso el formato esta bien pero el sis tiene mas de 9 digitos o menos de 9 digitos y deberia salir otro mensaje de error

**Comment by jh0nz** [comment]
yia
