### ISSUE TITLE
Validacion de hito - No se puede confirmar validacion

### ISSUE THREAD

**Issue by Richi78** [Api-programming-company/TisTracker#250]
Docente: josemourinho@fcyt.umss.edu.bo
Password: Docente1234*

Empresa: Software House

![image](https://github.com/user-attachments/assets/2600335a-1a8d-4290-91a6-cb71eb4e4073)

Pasos
1. Agregar resultado esperado, observado, observaciones, carry over si corresponde
2. Click en confirmar
3. Aceptar

Error: 500
error: "Undefined array key 0"

Opcional -> el snackbar sale a la derecha y no es muy visible

**Comment by KevinOmega** [comment]
Arreglado
