### ISSUE TITLE
Error visual en el home de estudiante

### ISSUE THREAD

**Issue by KevinOmega** [Api-programming-company/TisTracker#251]
![image](https://github.com/user-attachments/assets/0aebea66-f83b-4f0e-a871-d6ab1d3b5d80)

No sale centrado el cargando

![image](https://github.com/user-attachments/assets/f968caa1-c9a5-4bae-9fb3-d59999b715d7)

NO se ve nada de informacion en el home de estudiante

**Comment by erwinparedez** [comment]
Para qué cuenta @KevinOmega ??? No puedo replicar el bug. En el deployado con la cuenta 192168210@est.umss.edu (contraseña: Estudiante1234*) me salió correcto:

![image](https://github.com/user-attachments/assets/c0346318-5d9c-4ece-85a7-76f78238cd06)

![image](https://github.com/user-attachments/assets/360130d3-f42e-4d93-99f2-043fcccab9e6)

Para la cuenta 192168218@est.umss.edu me salió asi:
![image](https://github.com/user-attachments/assets/d2fb71ed-1184-4db7-8f53-ceff1614c4bd)

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/354625f9-2cc9-400d-a6a8-7d3f54f5f5ec)

![image](https://github.com/user-attachments/assets/570128f1-720a-43f6-aadf-2a7b984e2640)

Corregido, con botoncito de mi grupo empresa gigante :D

**Comment by Richi78** [comment]
@erwinparedez 
se esta controlando la fecha de conformacion de GE, te sale los botones porque aun estas en el rango de fechas, si quieres replicar modifica en la base de datos la fecha y veras que desaparecen los botoncitos
