### ISSUE TITLE
Crear evaluacion - No se puede crear

### ISSUE THREAD

**Issue by Richi78** [Api-programming-company/TisTracker#252]
Docente: josemourinho@fcyt.umss.edu.bo
Password: Docente1234*

Periodo academico en la base de datos -> id: 2

![image](https://github.com/user-attachments/assets/19760b35-80b3-49fc-aed0-d1232e1996bd)

Estoy en el rango de fechas y no se puede crear evaluacion, puse otras fechas intermedias y tampoco pude crear evaluaciones

**Comment by jh0nz** [comment]
ya esta
