### ISSUE TITLE
No hay retroalimentacion Al crear GrupoEmpresa ID:133

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#32]
![image](https://github.com/user-attachments/assets/f2ecebb7-434a-4706-9697-0d467c64e71d)
nombre largo repetido , nombre corto repetido, email repetido , numero repetido

**Comment by Frosmin** [comment]
no hay retroalimentación de ningún tipo

**Comment by jh0nz** [comment]
yia
