### ISSUE TITLE
Registrar estudiante case id 116

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#37]
![image](https://github.com/user-attachments/assets/2ddb5bf5-4a69-4963-8a57-07df8a01b35a)
En el mensaje de retroalimentación falta que diga, "que la contraseña no puede tener espacios" o algo asi test case id 116

**Comment by Frosmin** [comment]
lo mismo para docente

**Comment by jh0nz** [comment]
yia esta
