### ISSUE TITLE
¿Presionar el botón "Registrar" redirige al usuario a la página de inicio (Home) cuando los campos del formulario son válidos.? case id 431

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#38]
![image](https://github.com/user-attachments/assets/f5c0f0b1-4a41-447d-b250-67fc7ee55cde)
me redirige aquí

**Comment by Frosmin** [comment]
lo mismo para docente

**Comment by jh0nz** [comment]
cambia el criterio, esta bien que muestre el mensaje de exito
