### ISSUE TITLE
aceptar/ rechazar invitacion de grupo empresa 

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#45]
![image](https://github.com/user-attachments/assets/0fbec956-1ed2-401e-92b0-3ffdc7892802)
una vez aceptado la solicitud no te redirige a ningún lado, (puedes volver a aceptar la misma solicitud que ya aceptaste)

**Comment by Frosmin** [comment]
@Jh0nZ

**Comment by jh0nz** [comment]
yia esta

**Comment by Frosmin** [comment]
sigue mal

**Comment by Richi78** [comment]
@Frosmin ya deberia redirigir a '/', eso es un criterio?

**Comment by Frosmin** [comment]
no es un criterio, si ya esta cierren el issue
