### ISSUE TITLE
Enviar invitación a estudiantes para unirse a la grupo empresa

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#48]
![image](https://github.com/user-attachments/assets/887331bf-019b-405f-b035-90bd9fc49099)
Una vez enviada la invitación no redirige a ningún lugar ni sale mensaje de confirmación (no esta en los criterios)

**Comment by Frosmin** [comment]
sigue feo

**Comment by jh0nz** [comment]
se cambio
