### ISSUE TITLE
Aceptar conformación de Grupo-Empresa (ID: 287)

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#49]
![image](https://github.com/user-attachments/assets/5501ec65-93cd-4341-a3d4-ab1ce5430539)
¿Al Presionar el botón "Aceptar" muestra un mensaje indicando que la solicitud ha sido aceptada correctamente.?
no funciona, Tampoco redirige, no muestra retroalimentación de ningún tipo

**Comment by jh0nz** [comment]
yia esta
