### ISSUE TITLE
Aceptar conformación de Grupo-Empresa (ID: 287)

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#51]
![image](https://github.com/user-attachments/assets/f5e71fc3-4196-43ca-b6fb-8e53fecbaa09)
¿Al Presionar el botón "Rechazar" muestra un mensaje indicando que la Solicitud ha sido rechazada correctamente.?
Al pulsar el boton rechazar muestra mensaje incorrecto, también las solicitudes no se van se quedan

**Comment by Richi78** [comment]
@Frosmin  ahora?
