### ISSUE TITLE
Inscribirse a grupo TIS

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#74]
Cree un nuevo docente, cree su propio periodo académico
![image](https://github.com/user-attachments/assets/422e5047-ea4d-426a-9121-4aae28159f86)
inicia hoy, hoy es 14/10/2024
![image](https://github.com/user-attachments/assets/1f9634e9-ccf9-4ece-9c23-85cb8cf7db0d)
no aparece el periodo crear para inscribirse

**Comment by Frosmin** [comment]
importante reparar fast

**Comment by jh0nz** [comment]
![imagen](https://github.com/user-attachments/assets/9a61d792-977c-4747-a161-099e4666a3e0)
reporte bien

**Comment by Frosmin** [comment]
![image](https://github.com/user-attachments/assets/860468a4-6716-414c-82c4-c098e47f6a53)
Recién creado  
![image](https://github.com/user-attachments/assets/2de1a185-c9e5-46d3-b4b6-6730cfce69e6)
Sigue mal

**Comment by jh0nz** [comment]
ya esta
