### ISSUE TITLE
Registra grupo empresa

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#75]
![image](https://github.com/user-attachments/assets/2892b232-0a36-4b32-8de4-6a78ca98a313)
Estando en este periodo pasado (que ya acabo )

![image](https://github.com/user-attachments/assets/f3e265e5-8562-45f9-84d1-c78f8a115fd3)
salen mensajes sin sentido

Tambien se crearon estas empresas en la base de datos 
![image](https://github.com/user-attachments/assets/c5500493-1289-4c5b-a1a6-2d635c6ae2a6)

en el periodo académico de id 4

**Comment by jh0nz** [comment]
ya esta
