### ISSUE TITLE
Ajustar periodo de entrega final

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#76]
![image](https://github.com/user-attachments/assets/39f769e2-1257-4039-be97-9d5399d5240c)
No cumple con lógica de negocio
meses fuera del semestrw

**Comment by jh0nz** [comment]
Se calcula si el periodo académico dura más de 6 meses. Si la fecha de fin es posterior a 6 meses desde la fecha de inicio, se devuelve un mensaje de error indicando que no puede durar más de 6 meses (422).

actualizar criterios 🐈
