### ISSUE TITLE
Invitar a GE

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#79]
![image](https://github.com/user-attachments/assets/39480415-7d7b-434c-b6a5-b866166a5a1c)
con el user encargado de empresa/creador de empresa
100000000@est.umss.edu
Pass : Simon123@

No deja invitar a 
200000000@est.umss.edu
que se encuentra en el mismo periodo academico

**Comment by jh0nz** [comment]
ya esta
