### ISSUE TITLE
Crear planificación 

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#80]
![image](https://github.com/user-attachments/assets/bc59d1d7-6be1-4f70-af5d-43f3f5be3206)
con el user encargado de empresa/creador de empresa
[100000000@est.umss.edu](mailto:100000000@est.umss.edu)
Pass : Simon123@

Sin agregar nada se pulsa el botón confirmar 
Mensaje de retroalimentación poco descriptivo

**Comment by jh0nz** [comment]
@KevinOmega @KevinOmega @KevinOmega @KevinOmega @KevinOmega  no te olvides de arreglar
