### ISSUE TITLE
Crear Plantilla de Evaluación

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#81]
![image](https://github.com/user-attachments/assets/a3426fcf-cfe5-4e9e-98d6-612925656acd)
Error inconsitene en los recuadros **nombre de plantilla , Descripción**

user: Cualquier docente creando una planitlla

**Comment by jh0nz** [comment]
no es random, no debe enviarse el formulario hasta que pase por validaciones del front @Richi78

**Comment by Richi78** [comment]
de ser bug no es, solo puse el snackbar con ese mensaje para que en caso de que exista muchos criterios pueda tener retroalimentacion clara, en ahi el formulario no se esta enviando quiza puedo cambiar el mensaje a uno mas claro

**Comment by jh0nz** [comment]
> de ser bug no es, solo puse el snackbar con ese mensaje para que en caso de que exista muchos criterios pueda tener retroalimentacion clara, en ahi el formulario no se esta enviando quiza puedo cambiar el mensaje a uno mas claro

Esta bien

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/97b4ec20-d9d3-4daa-928a-62e32a595f57)
