### ISSUE TITLE
Crear Plantilla de Evaluación

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#82]
![image](https://github.com/user-attachments/assets/d7473ba4-5557-41ab-a41c-b1bad172542d)
Todos los datos cumplen(no se muestra ningún error ) puede que falte conexión con el back

User: simon@fcyt.umss.edu.bo
pass: Simon123@

**Comment by Frosmin** [comment]
![image](https://github.com/user-attachments/assets/7dff93ec-c2e0-4a88-877f-0707f6b6e1d5)
Borre el criterio con multiples parámetros  y funciono xd

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/1b0ccc85-b0e9-4aa4-b18d-59c64975fa19)
