### ISSUE TITLE
Crear plantilla de evaluacion

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#83]
![image](https://github.com/user-attachments/assets/fb8ade7e-acd9-4aff-aeb8-7de48ea711fb)
Se pueden poner parámetros Iguales

User :simon@fcyt.umss.edu.bo
Pass : Simon123q

**Comment by jh0nz** [comment]
Front @Richi78

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/7dd6d11f-69aa-4df5-9d60-a958d61bbb4f)
