### ISSUE TITLE
Crear plantilla de evaluacion

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#84]
![image](https://github.com/user-attachments/assets/1e1e02f2-d92a-4be3-b1ff-c85016784879)
se pueden crear criterios con en mimos nombre

User: simon@fcyt.umss.edu.bo
Pass: Simon123@

**Comment by jh0nz** [comment]
Front @Richi78

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/ae832421-6a22-456f-96c6-2f28d0eb0555)
