### ISSUE TITLE
Ver plantilla de evaluacion/ Crear plantilla de evaluación 

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#85]
![image](https://github.com/user-attachments/assets/36f4d1fe-f4b1-4a4a-9307-3a0855d688d9)
Se pueden crear 2 plantillas con el mismo nombre y la mima descripcion, el docente se va a lokiar intentado encontrar su plantilla correcta

**Comment by jh0nz** [comment]
Falta mostrar el error en el front @Richi78

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/10c6b7c5-b7a1-4b56-8b52-af79daa865a5)
ya controla el nombre de la plantilla si esta en uso, hay que cambiar el mensaje de error de validación a uno que especifique ese ese nombre ya esta en uso @Jh0nZ

**Comment by jh0nz** [comment]
ya esta en errors, tienes que mostrarlo como error en el input del nombre @Richi78, luego cambio name a nombre

**Comment by Richi78** [comment]
![image](https://github.com/user-attachments/assets/eb234a79-f1b6-42b3-b897-00290d952286)
