### ISSUE TITLE
Ver invitaciones GE

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#87]
![image](https://github.com/user-attachments/assets/1abe85e6-bcd3-4152-b597-01a00796dc8b)
Usuarios invitados por
User 100000000@est.umss.edu
pass Simon123@

![image](https://github.com/user-attachments/assets/abb77de3-b25a-4716-b755-4d3d8c903815)
No le llegan las invitaciones al usuario 
User 200000000@est.umss.edu
pass Simon123@

**Comment by jh0nz** [comment]
ya
