### ISSUE TITLE
Ver invitaciones GE

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#89]
La fecha esta adelantada un día, siendo que la invitación se mando hoy (como se puede ver en la fotito :D)

![Captura de pantalla 2024-10-18 162605](https://github.com/user-attachments/assets/e5ef3900-62e2-4436-96b5-5d2de1db6b49)

User 200000000@est.umss.edu
Pass: Simon123@

**Comment by Frosmin** [comment]
@Jh0nZ te dije que estaba la fecha mal

**Comment by jh0nz** [comment]
@Frosmin estoy aprendiendo XDefiant

**Comment by jh0nz** [comment]
ya esta
