### ISSUE TITLE
Retirar invitaciones a grupo empresa / invitar de nuevo 

### ISSUE THREAD

**Issue by Frosmin** [Api-programming-company/TisTracker#90]
![image](https://github.com/user-attachments/assets/bccded20-e78e-4da9-a69f-463449e0d19b)
User 100000000@est.umss.edu
pass Simon123q

se invita al usuario 300000000@est.umss.edu, luego se le retira la invitación, y el admin de la empresa quiere volverlo a invitar pero ya nose puede D:

**Comment by jh0nz** [comment]
ya esta
